In [77]:
import numpy as np
import pandas as pd
import torch

In [17]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([[1],[2],[3],[4]])
c = -10*np.array([[1],[2],[3],[4]])
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]
 [4]]


In [16]:
print(a@b)

[[ 30]
 [ 70]
 [110]]


In [14]:
prueba = 0
for i in range(4):
    prueba = prueba+a[0,i]*b[i]
    print(a[0,i], b[i])

1 [1]
2 [2]
3 [3]
4 [4]


In [15]:
print(prueba)

[30]


In [19]:
d = np.absolute(b+c)
d

array([[ 9],
       [18],
       [27],
       [36]])

In [22]:
b[i][0]*a[0,1]

8

In [42]:
np.random.seed(10)

In [43]:
x = np.random.rand(100,20)

In [44]:
p = np.random.rand(100)

In [45]:
y = x.T@p

In [51]:
y[0]


21.162396272866168

In [52]:
z = 0.0
for i in range(100):
    z = z+x[i,0]*p[i]

In [53]:
print(z)

21.162396272866168


In [54]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([[1],[2],[3],[4]])

In [57]:
c = np.array([1,2,3,4])

In [58]:
d = c+b

In [60]:
e = np.array([[1],[2],[3],[4]])

In [61]:
f = e+b

In [62]:
f

array([[2],
       [4],
       [6],
       [8]])

In [66]:
(f**2).sum()

120

In [67]:
f**2


array([[ 4],
       [16],
       [36],
       [64]])

In [70]:
a
b = a*2



In [71]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
d = np.array([[3,4,5],[2,1,6]])

In [73]:
f = d@(a-b)

In [74]:
f


array([[ -68,  -80,  -92, -104],
       [ -61,  -70,  -79,  -88]])

In [75]:
a-b

array([[ -1,  -2,  -3,  -4],
       [ -5,  -6,  -7,  -8],
       [ -9, -10, -11, -12]])

In [76]:
d

array([[3, 4, 5],
       [2, 1, 6]])